### ISSUE TITLE
Redo the Product page 

### ISSUE THREAD

**Issue by hubertle43100** [hubertle43100/minimal-ecommerce#27]
### When you click the drink 
I want to display it in a way that represents this `inspiration from dribbble`

![Screenshot 2024-02-15 at 10 54 06 AM](https://github.com/hubertle43100/minimal-ecommerce/assets/56861838/853a49d0-ead8-4395-bb46-fee4c2c045f4)

**Feb 15th update**
`Here is a complete checklist for the product page because I think it is important`
- [x] #24 Change header
- [x] #22 Reduce to one picture of the product
- [x] #9 Make a back button on to drink page
- [x] #29 Changing the top part of the product page
- [x] #32 Choose sticker option

**Comment by hubertle43100** [comment]
Almost finalized the products page needs to change text to bring more focus to choosing options

- `Kinda want to change the theme of the page`

![Screenshot 2024-02-15 at 3 42 48 PM](https://github.com/hubertle43100/minimal-ecommerce/assets/56861838/0e68b618-88a1-4b4d-97ab-7c2e66f451d4)

**Comment by hubertle43100** [comment]
### Some issues related to this entire theme change
- [ ] #18
